//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseToSql.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataverseToSql.Core.SqlObjects", typeof(SqlObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[BlobsToIngest_Complete]
        ///	@EntityName [DataverseToSql].[EntityType],
        ///	@BlobName [DataverseToSql].[BlobNameType]
        ///AS
        ///
        ///-- Set complete to 1 if the blob load type is &quot;full&quot;
        ///UPDATE	[DataverseToSql].[BlobsToIngest]
        ///SET		[Complete] = 1
        ///WHERE
        ///		[EntityName] = @EntityName
        ///		AND [BlobName] = @BlobName
        ///		AND [LoadType] = 0 -- Full
        ///
        ///-- Delete the blob record if the load is &quot;incremental&quot;
        ///DELETE	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_BlobsToIngest_Complete_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_BlobsToIngest_Complete_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[BlobsToIngest_Get]
        ///AS
        ///SELECT
        ///	[EntityName],
        ///	[BlobName],
        ///	[TargetSchema],
        ///	[TargetTable],
        ///	[ServerlessQuery],
        ///	[LoadType]
        ///FROM
        ///	[DataverseToSql].[BlobsToIngest]
        ///WHERE
        ///	[Complete] = 0
        ///ORDER BY
        ///	[BlobName].
        /// </summary>
        internal static string DataverseToSql_BlobsToIngest_Get_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_BlobsToIngest_Get_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[BlobsToIngest_Insert]
        ///	@EntityName [DataverseToSql].[EntityType],
        ///	@BlobName [DataverseToSql].[BlobNameType],
        ///	@TargetSchema SYSNAME,
        ///	@TargetTable SYSNAME,
        ///	@ServerlessQuery NVARCHAR(MAX),
        ///	@LoadType INT
        ///AS
        ///IF NOT EXISTS (
        ///	SELECT * FROM [DataverseToSql].[BlobsToIngest]
        ///	WHERE
        ///		[EntityName] = @EntityName
        ///		AND [BlobName] = @BlobName
        ///)
        ///BEGIN
        ///	INSERT INTO [DataverseToSql].[BlobsTo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_BlobsToIngest_Insert_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_BlobsToIngest_Insert_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [DataverseToSql].[BlobsToIngest] (
        ///	[Id] INT IDENTITY PRIMARY KEY,
        ///	[EntityName] [DataverseToSql].[EntityType] NOT NULL,
        ///	[BlobName] [DataverseToSql].[BlobNameType] NOT NULL,
        ///	[TargetSchema] SYSNAME NOT NULL,
        ///	[TargetTable] SYSNAME NOT NULL,
        ///	[ServerlessQuery] NVARCHAR(MAX) NOT NULL,
        ///	[LoadType] INT NOT NULL,
        ///	[Complete] INT NOT NULL DEFAULT 0,
        ///	CONSTRAINT UQ_BlobsToIngest UNIQUE ([EntityName], [BlobName]),        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_BlobsToIngest_Table {
            get {
                return ResourceManager.GetString("DataverseToSql_BlobsToIngest_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[FullLoad_Complete]
        ///AS
        ///BEGIN TRAN
        ///
        ///DECLARE @CompletedEntities TABLE(
        ///	[EntityName] [DataverseToSql].[EntityType]
        ///)
        ///
        ///UPDATE [DataverseToSql].[ManagedEntities]
        ///SET [State] = 3 -- Ready
        ///OUTPUT inserted.[EntityName] 
        ///	INTO @CompletedEntities
        ///WHERE [EntityName] IN (
        ///	SELECT
        ///		[EntityName]
        ///	FROM
        ///		[DataverseToSql].[BlobsToIngest]
        ///	GROUP BY
        ///		[EntityName]
        ///	HAVING
        ///		MIN([Complete]) =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_FullLoad_Complete_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_FullLoad_Complete_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [DataverseToSql].[ManagedBlobs] (
        ///	[EntityName] [DataverseToSql].[EntityType] NOT NULL,
        ///	[BlobName] [DataverseToSql].[BlobNameType] NOT NULL,
        ///	[FileOffset] BIGINT NOT NULL,
        ///	CONSTRAINT PK_ManagedBlobs PRIMARY KEY ([EntityName], [BlobName]),
        ///	CONSTRAINT FK_ManagedBlobs_Entities FOREIGN KEY ([EntityName]) REFERENCES [DataverseToSql].[ManagedEntities]([EntityName])
        ///);.
        /// </summary>
        internal static string DataverseToSql_ManagedBlobs_Table {
            get {
                return ResourceManager.GetString("DataverseToSql_ManagedBlobs_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[ManagedBlobs_Upsert]
        ///	@EntityName [DataverseToSql].[EntityType],
        ///	@BlobName [DataverseToSql].[BlobNameType],
        ///	@FileOffset BIGINT
        ///AS
        ///IF NOT EXISTS (
        ///	SELECT * FROM [DataverseToSql].[ManagedBlobs]
        ///	WHERE
        ///		[EntityName] = @EntityName
        ///		AND [BlobName] = @BlobName
        ///)
        ///BEGIN
        ///	INSERT INTO [DataverseToSql].[ManagedBlobs](
        ///		[EntityName],
        ///		[BlobName],
        ///		[FileOffset]
        ///	)
        ///	VALUES (
        ///		@Entit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_ManagedBlobs_Upsert_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_ManagedBlobs_Upsert_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [DataverseToSql].[ManagedCustomScripts] (
        ///	[ScriptName] [DataverseToSql].[CustomScriptNameType] NOT NULL PRIMARY KEY,
        ///	[Hash] NVARCHAR(128) NULL
        ///).
        /// </summary>
        internal static string DataverseToSql_ManagedCustomScripts_Table {
            get {
                return ResourceManager.GetString("DataverseToSql_ManagedCustomScripts_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[ManagedCustomScripts_Upsert]
        ///	@ScriptName [DataverseToSql].[CustomScriptNameType],
        ///	@Hash  NVARCHAR(128)
        ///AS
        ///IF NOT EXISTS (
        ///	SELECT * FROM [DataverseToSql].[ManagedCustomScripts]
        ///	WHERE
        ///		[ScriptName] = @EntityName
        ///)
        ///BEGIN
        ///	INSERT INTO [DataverseToSql].[ManagedCustomScripts](
        ///		[ScriptName],
        ///		[Hash]
        ///	)
        ///	VALUES (
        ///		@ScriptName,
        ///		@Hash
        ///	)
        ///END
        ///ELSE
        ///BEGIN
        ///	UPDATE [DataverseToS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_ManagedCustomScripts_Upsert_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_ManagedCustomScripts_Upsert_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [DataverseToSql].[ManagedEntities] (
        ///	[EntityName] [DataverseToSql].[EntityType] NOT NULL PRIMARY KEY,
        ///	[State] INT NOT NULL,
        ///	[SchemaHash] NVARCHAR(128) NULL
        ///).
        /// </summary>
        internal static string DataverseToSql_ManagedEntities_Table {
            get {
                return ResourceManager.GetString("DataverseToSql_ManagedEntities_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE PROCEDURE [DataverseToSql].[ManagedEntities_Upsert]
        ///	@EntityName [DataverseToSql].[EntityType],
        ///	@State INT = NULL,
        ///	@SchemaHash NVARCHAR(128) = NULL
        ///AS
        ///IF NOT EXISTS (
        ///	SELECT * FROM [DataverseToSql].[ManagedEntities]
        ///	WHERE [EntityName] = @EntityName
        ///)
        ///BEGIN
        ///	INSERT INTO [DataverseToSql].[ManagedEntities](
        ///		[EntityName],
        ///		[State],
        ///		[SchemaHash]
        ///	)
        ///	VALUES (
        ///		@EntityName,
        ///		@State,
        ///		@SchemaHash
        ///	)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataverseToSql_ManagedEntities_Upsert_Proc {
            get {
                return ResourceManager.GetString("DataverseToSql_ManagedEntities_Upsert_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE SCHEMA [DataverseToSql];.
        /// </summary>
        internal static string DataverseToSql_Schema {
            get {
                return ResourceManager.GetString("DataverseToSql_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TYPE [DataverseToSql].[EntityType]
        ///	FROM NVARCHAR(128);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[BlobNameType]
        ///	FROM NVARCHAR(722);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[CustomScriptNameType]
        ///	FROM NVARCHAR(512);
        ///GO
        ///.
        /// </summary>
        internal static string DataverseToSql_Types {
            get {
                return ResourceManager.GetString("DataverseToSql_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [$$SCHEMA$$].[GlobalOptionsetMetadata] (
        ///	[OptionSetName] [varchar](128) NULL,
        ///	[Option] [bigint] NULL,
        ///	[IsUserLocalizedLabel] [varchar](6) NULL,
        ///	[LocalizedLabelLanguageCode] [bigint] NULL,
        ///	[LocalizedLabel] [varchar](700) NULL,
        ///	[GlobalOptionSetName] [varchar](128) NULL,
        ///	[EntityName] [varchar](128) NULL
        ///);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[GlobalOptionsetMetadata_TableType] AS TABLE (
        ///	[OptionSetName] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Optionsets_GlobalOptionsetMetadata {
            get {
                return ResourceManager.GetString("Optionsets_GlobalOptionsetMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [$$SCHEMA$$].[OptionsetMetadata] (
        ///	[EntityName] [varchar](128) NULL,
        ///	[OptionSetName] [varchar](128)  NULL,
        ///	[Option] [bigint] NULL,
        ///	[IsUserLocalizedLabel] [varchar](6) NULL,
        ///	[LocalizedLabelLanguageCode] [bigint] NULL,
        ///	[LocalizedLabel] [varchar](700)  NULL
        ///);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[OptionsetMetadata_TableType] AS TABLE (
        ///	[EntityName] [varchar](128) NULL,
        ///	[OptionSetName] [varchar](128)  NU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Optionsets_OptionsetMetadata {
            get {
                return ResourceManager.GetString("Optionsets_OptionsetMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [$$SCHEMA$$].[StateMetadata] (
        ///	[EntityName] [varchar](128) NULL,
        ///	[State] [bigint] NULL,
        ///	[IsUserLocalizedLabel] [varchar](6) NULL,
        ///	[LocalizedLabelLanguageCode] [bigint] NULL,
        ///	[LocalizedLabel] [varchar](700) NULL
        ///);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[StateMetadata_TableType] AS TABLE (
        ///	[EntityName] [varchar](128) NULL,
        ///	[State] [bigint] NULL,
        ///	[IsUserLocalizedLabel] [varchar](6) NULL,
        ///	[LocalizedLabel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Optionsets_StateMetadata {
            get {
                return ResourceManager.GetString("Optionsets_StateMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [$$SCHEMA$$].[StatusMetadata] (
        ///	[EntityName] [varchar](128) NULL,
        ///	[State] [bigint] NULL,
        ///	[Status] [bigint] NULL,
        ///	[IsUserLocalizedLabel] [varchar](6) NULL,
        ///	[LocalizedLabelLanguageCode] [bigint] NULL,
        ///	[LocalizedLabel] [varchar](700) NULL
        ///);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[StatusMetadata_TableType] AS TABLE (
        ///	[EntityName] [varchar](128) NULL,
        ///	[State] [bigint] NULL,
        ///	[Status] [bigint] NULL,
        ///	[IsUs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Optionsets_StatusMetadata {
            get {
                return ResourceManager.GetString("Optionsets_StatusMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Copyright (c) Microsoft Corporation.
        ///-- Licensed under the MIT License.
        ///
        ///CREATE TABLE [$$SCHEMA$$].[TargetMetadata] (
        ///	[EntityName] [varchar](128) NULL,
        ///	[AttributeName] [varchar](128) NULL,
        ///	[ReferencedEntity] [varchar](128) NULL,
        ///	[ReferencedAttribute] [varchar](128) NULL
        ///);
        ///GO
        ///
        ///CREATE TYPE [DataverseToSql].[TargetMetadata_TableType] AS TABLE (
        ///	[EntityName] [varchar](128) NULL,
        ///	[AttributeName] [varchar](128) NULL,
        ///	[ReferencedEntity] [varchar](128) NULL,
        ///	[ReferencedAttribute] [varchar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Optionsets_TargetMetadata {
            get {
                return ResourceManager.GetString("Optionsets_TargetMetadata", resourceCulture);
            }
        }
    }
}
